### ISSUE TITLE
Add ES5 rules

### ISSUE THREAD

**Issue by ai** [logux/eslint-config#1]
Allow only `var` and deny arrow functions.

**Comment by Semigradsky** [comment]
https://github.com/NatureFeng/eslint-plugin-no-es2015

**Comment by ai** [comment]
@Semigradsky great! Do you want to send PR with that plugin to this config?

**Comment by ai** [comment]
@Semigradsky also maybe this author need a help with a docs? Do you want to help him? 
https://github.com/NatureFeng/eslint-plugin-no-es2015/issues/1

**Comment by ai** [comment]
@nkt wrote much better plugin — more rules and tests https://github.com/nkt/eslint-plugin-es5

I think we will use it. I am just waiting for few small fixes in his PR.

**Comment by ai** [comment]
Done by @nkt https://github.com/logux/eslint-config-logux/pull/2
