### ISSUE TITLE
'jest/no-empty-title' was not found

### ISSUE THREAD

**Issue by vrizo** [logux/eslint-config#12]
Hi, @ai!

Thanks for the best code style! 😍 

I noticed that there is an error `'jest/no-empty-title' was not found` after upgrading to the latest `eslint-plugin-jest`. The rule was replaced with a fantastic `jest/valid-title`.

- [Here](https://github.com/jest-community/eslint-plugin-jest/commit/bb2d09ea2084c12d6dc0b6fdb88c1fa8fa897273) is a commit with the breaking change

Please consider replacing `no-empty-title` with `valid-title`.

Thank you!

**Comment by ai** [comment]
Fixed f5b9ce4

**Comment by ai** [comment]
Released in 34.0 with few new rules :)

**Comment by vrizo** [comment]
Thanks for your quick response, @ai!
