### ISSUE TITLE
Improve docs: specify the usage of flat config

### ISSUE THREAD

**Issue by vrizo** [logux/eslint-config#19]
Hi @ai ,

Long time no see. I still use these code styles for my pet projects. I was puzzled when I couldn't start using the updated version because of unclear errors in the console:

```bash
eslintrc:config-array-factory Error reading package.json file: /package.json
eslintrc:config-array-factory Config file not found on /
eslintrc:cascading-config-array-factory No cache found: /.
```

and so on.

That's because I didn't notice that you've moved to a flat configuration in ESLint, which Visual Studio Code still doesn't support by default. I needed to enable a `useFlatConfig` flag for this specific project to fix the issue.

Moreover, in case of improper configuration, if a valid eslint config is found in one of the parent folders, it's used instead of `eslint.config.js`, which is super unclear.

Please consider adding a notice to docs that the flat config support should be enabled in the editor.

See you!

**Comment by ai** [comment]
> Please consider adding a notice to docs that the flat config support should be enabled in the editor.

Good idea. Can you send PR to docs?

**Comment by vrizo** [comment]
> Can you send PR to docs?

Thanks for your quick reply! I've created a [PR](https://github.com/logux/eslint-config/pull/20).
